# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 07:26
from __future__ import unicode_literals

import dj_bioinformatics_protein.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_query_sequence', dj_bioinformatics_protein.fields.AminoAcidSequenceTextField(max_length=5000)),
                ('query_aln_seq', dj_bioinformatics_protein.fields.AminoAcidAlignmentTextField(max_length=5000)),
                ('alignment_method', models.CharField(choices=[(b'H', b'hhsearch'), (b'S', b'sparksX'), (b'U', b'user')], max_length=1)),
                ('rank', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('query_start', models.IntegerField()),
                ('query_description', models.CharField(max_length=1000, null=True)),
                ('modified_query_aln_seq', dj_bioinformatics_protein.fields.AminoAcidAlignmentTextField(max_length=5000, null=True)),
                ('target_start', models.IntegerField()),
                ('target_description', models.CharField(max_length=1000, null=True)),
                ('target_pdb_code', models.CharField(max_length=4)),
                ('target_pdb_chain', models.CharField(max_length=1)),
                ('target_aln_seq', dj_bioinformatics_protein.fields.AminoAcidAlignmentTextField(max_length=5000)),
                ('modified_target_aln_seq', dj_bioinformatics_protein.fields.AminoAcidAlignmentTextField(max_length=5000, null=True)),
                ('p_correct', models.FloatField()),
                ('threaded_template', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FASTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('comments', models.TextField(null=True)),
                ('sequence', dj_bioinformatics_protein.fields.AminoAcidSequenceTextField(max_length=5000)),
            ],
        ),
    ]
