# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 22:42
from __future__ import unicode_literals

import dj_bioinformatics_protein.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'dj_bioinformatics_protein', '0001_initial'), (b'dj_bioinformatics_protein', '0002_remove_alignment_sha256'), (b'dj_bioinformatics_protein', '0003_auto_20160227_0008'), (b'dj_bioinformatics_protein', '0004_auto_20170621_1918')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_method', models.CharField(choices=[('H', 'hhsearch'), ('S', 'sparksX'), ('U', 'user')], max_length=1)),
                ('rank', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('query_start', models.IntegerField()),
                ('query_aln_seq', dj_bioinformatics_protein.fields.AminoAcidAlignmentField(max_length=5000, validators=[django.core.validators.RegexValidator('^[ACDEFGHIKLMNPQRSTVWYX\\-]*$', 'Only uppercase amino acid abbreviations or dashes are allowed, or X (non canonical residues).')])),
                ('modified_query_aln_seq', dj_bioinformatics_protein.fields.AminoAcidAlignmentField(max_length=5000, null=True, validators=[django.core.validators.RegexValidator('^[ACDEFGHIKLMNPQRSTVWYX\\-]*$', 'Only uppercase amino acid abbreviations or dashes are allowed, or X (non canonical residues).')])),
                ('target_pdb_code', models.CharField(max_length=4)),
                ('target_pdb_chain', models.CharField(max_length=1)),
                ('target_start', models.IntegerField()),
                ('target_aln_seq', dj_bioinformatics_protein.fields.AminoAcidAlignmentField(max_length=5000, validators=[django.core.validators.RegexValidator('^[ACDEFGHIKLMNPQRSTVWYX\\-]*$', 'Only uppercase amino acid abbreviations or dashes are allowed, or X (non canonical residues).')])),
                ('modified_target_aln_seq', dj_bioinformatics_protein.fields.AminoAcidAlignmentField(max_length=5000, null=True, validators=[django.core.validators.RegexValidator('^[ACDEFGHIKLMNPQRSTVWYX\\-]*$', 'Only uppercase amino acid abbreviations or dashes are allowed, or X (non canonical residues).')])),
                ('p_correct', models.FloatField()),
                ('threaded_template', models.TextField(blank=True, null=True)),
                ('full_query_sequence', dj_bioinformatics_protein.fields.AminoAcidSequenceField(max_length=5000, validators=[django.core.validators.RegexValidator('^[ACDEFGHIKLMNPQRSTVWYX]*$', 'Only uppercase amino acid abbreviations are allowed, or X (non canonical residues).')])),
                ('query_description', models.CharField(max_length=1000, null=True)),
                ('target_description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FASTA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('comments', models.TextField(null=True)),
                ('sequence', dj_bioinformatics_protein.fields.AminoAcidSequenceField(max_length=5000, validators=[django.core.validators.RegexValidator('^[ACDEFGHIKLMNPQRSTVWYX]*$', 'Only uppercase amino acid abbreviations are allowed, or X (non canonical residues).')])),
            ],
        ),
    ]
