# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_bioinformatics_protein', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='sha256',
        ),
    ]
